version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain wb-tdp --domain-owner 580753801134 --region ap-south-1 --query authorizationToken --output text`
    - mvn -s settings.xml clean package deploy
  post_build:
    commands:
    - echo Build completed on `date`