version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain ${CODEARTIFACT_DOMAIN} --domain-owner ${AWS_ACCOUNT_ID} --region ${AWS_REGION} --query authorizationToken --output text`
    - mvn -s settings.xml clean package deploy -DaltDeploymentRepository=wb-tdp-framework-repo::https://wb-tdp-580753801134.d.codeartifact.ap-south-1.amazonaws.com/maven/framework-repo/
  post_build:
    commands:
    - echo Build completed on `date`
